FROM python:3.9

WORKDIR /src
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r /requirements.txt

EXPOSE {{ PORT|default(8080, true) }}

ENTRYPOINT ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "{{ PORT|default(8080, true) }}"]