FROM python:3.9

COPY requirements.txt /requirements.txt
RUN ln -sf /usr/share/zoneinfo/Europe/Rome /etc/timezone && \
    ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime && \
    apt-get update && apt-get install -y \
    build-essential \
    python3-dev

RUN pip3 install --no-cache-dir -r /requirements.txt

WORKDIR /src

EXPOSE 8080

ENTRYPOINT ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]